name: Deploy to sklepik-production
run-name: Deploying code to sklepik-production...
on: [push]
jobs:
    Test-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Setup node
              uses: actions/setup-node@v4

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              working-directory: ./frontend
              run: npm install

            - name: Test code
              working-directory: ./frontend
              run: npm run test

    Build-and-deploy:
        needs: Test-frontend
        runs-on: ubuntu-latest
        steps:
            - name: Setup node
              uses: actions/setup-node@v4

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install backend dependecies
              working-directory: ./backend
              run: npm install

            - name: Install frontend dependencies
              working-directory: ./frontend
              run: npm install

            - name: Build frontend
              working-directory: ./frontend
              run: npm run build

            - name: Copy frontend build to backend
              run: cp -r ./frontend/dist ./backend/dist

            - name: Push to production repository
              run: |
                  git config --global user.name "Github Actions"
                  git config --global user.email "imanoryk6@gmail.com"
                  git clone ${{secrets.PRODUCTION_REPOSITORY}}
                  rm -rf ./test/*
                  cp -r ./backend ./test
                  cd ./test
                  git add .
                  git commit -m "production build"
                  git push
