name: Deploy to sklepik-production
run-name: Deploying code to sklepik-production...
on: [push]
jobs:
    Test-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Setup node
              uses: actions/setup-node@v4

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              working-directory: ./frontend
              run: npm install

            - name: Test code
              working-directory: ./frontend
              run: npm run test

    Build-and-deploy:
        needs: Test-frontend
        runs-on: ubuntu-latest
        steps:
            - name: Setup node
              uses: actions/setup-node@v4

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install backend dependecies
              working-directory: ./backend
              run: npm install

            - name: Install frontend dependencies
              working-directory: ./frontend
              run: npm install

            - name: Build frontend
              working-directory: ./frontend
              run: npm run build

            - name: Copy frontend build to backend
              run: cp -r ./frontend/dist ./backend/dist

            - name: Push to production repository
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
              with:
                  source-directory: './backend'
                  destination-github-username: 'llgor34'
                  destination-repository-name: 'test'
                  user-email: imanoryk6@gmail.com
                  target-branch: main
